#!/usr/bin/php
<?php

require_once('dpc/system/pcntlcmd.lib.php'); 
$page = &new pcntl('
super rcserver.rcssystem;

load_extension adodb refby _ADODB_; 	
super database.database;

#---------------------------------load and create libs
#use xwindow.window,xwindow.window2;

#---------------------------------load not create dpc (internal use)
networlds.clientdpc;
			

#---------------------------------load all and create after dpc objects
frontpage.fronthtmlpage;
mail.smtpmail;
shop.rctranssql;

',0);	 

$ret = GetGlobal('controller')->calldpc_method('rctranssql.sync_sql use 1');
echo $ret;
//echo $page->render();
?>
