#!/usr/bin/php
<?php
$data = @file_get_contents('http://dl.dropbox.com/u/106627024/skroutz.xml');
//echo $data;
$utfdata = mb_convert_encoding($data, 'UTF-8', 'ISO-8859-7');
echo $utfdata;

$to = getcwd() . '/../skroutz.xml';
file_put_contents($to,trim($utfdata, "\t\n\r\0\x0B"));
echo $to,'>home/stereobi/public_html/basis/skroutz.xml';
?>