#!/usr/bin/php
<?php
define('SMTP_PHPMAILER','true');

require_once('dpc/system/pcntlcmd.lib.php'); 

$page = &new pcntl('
super rcserver.rcssystem;

load_extension adodb refby _ADODB_; 	
super database.database;

#---------------------------------load and create libs
#use xwindow.window,xwindow.window2;

#---------------------------------load not create dpc (internal use)
networlds.clientdpc;	

#---------------------------------load all and create after dpc objects
frontpage.fronthtmlpage;
mail.smtpmail;
private shop.rctranssql /cgi-bin;

',0);	 

$ret = GetGlobal('controller')->calldpc_method('rctranssql.sync_sql use 1+iso8859-7+utf-8'); //insert records from remote files
$ret .= GetGlobal('controller')->calldpc_method('rctranssql.run_sql use +1');//execute sql
echo $ret;
//echo $page->render();
?>