#!/usr/bin/php
<?php
$start=microtime(true);
/*** adodb4 (prev ver) for pcntlcmd (!?) ***/

require_once('dpc2/system/pcntlcmd.lib.php'); 
$page = &new pcntl('
super rcserver.rcssystem;

load_extension adodb4 refby _ADODB_; 
super database;

use mail.bounce_driver;

public frontpage.fronthtmlpage;
public mail.smtpmail;
public bmail.maildbqueue;
public bmail.rcbmailbounce;

',0);	 

//root app
$ret = GetGlobal('controller')->calldpc_method("rcbmailbounce.cleanBounce use +1"); //+1 //for del
echo $ret;

$apps = GetGlobal('controller')->calldpc_var('maildbqueue.app_pool');
if (!empty($apps)) {
  foreach ($apps as $i=>$app) {
    echo $app,'<br/>';
	$ret = GetGlobal('controller')->calldpc_method("rcbmailbounce.cleanBounce use $app+1+1");
	echo $ret;
  }
}
$time = (microtime(true) - $start)/60;//5.4$_SERVER["REQUEST_TIME_FLOAT"]);// /60;
echo "<!-- 	$time -->";
?>