#!/usr/bin/php
<?php
//define('SMTP_PHPMAILER','true');
define('SENDMAIL_PHPMAILER','true');

/*** adodb4 (prev ver) for pcntlcmd (!?) ***/

require_once('dpc2/system/pcntlcmd.lib.php'); 
$page = &new pcntl('
super rcserver.rcssystem;

load_extension adodb4 refby _ADODB_; 
super database;

use mail.bounce_driver;

public frontpage.fronthtmlpage;
public mail.smtpmail;
public bmail.maildbqueue;

',0);	 

$ret = GetGlobal('controller')->calldpc_method('maildbqueue.sendmail_daemon use 20+200');//20,400
echo $ret;
//echo $page->render();
?>