#!/usr/bin/php
<?php
$start=microtime(true);
/*** adodb4 (prev ver) for pcntlcmd (!?) ***/

require_once('dpc/system/pcntl.lib.php'); 
$page = &new pcntl('
super javascript;

load_extension adodb4 refby _ADODB_; 
super database;

use mail.bounce_driver;

public cms.cmsrt;
public mail.smtpmail;
public bmail.maildbqueue;
public bmail.rcbmailbounce;

',1,true);	 

//root app
$ret = _m("rcbmailbounce.cleanBounce use +1"); //+1 //for del
echo $ret;

$apps = _v('maildbqueue.app_pool');
if (!empty($apps)) {
  foreach ($apps as $i=>$app) {
    echo $app,'<br/>';
	$ret = _m("rcbmailbounce.cleanBounce use $app+1+1");
	echo $ret;
  }
}
$time = (microtime(true) - $start)/60;//5.4$_SERVER["REQUEST_TIME_FLOAT"]);// /60;
echo "<!-- 	$time -->";
?>