#!/usr/bin/php
<?php
$start=microtime(true);
//define('SMTP_PHPMAILER','true');
define('SENDMAIL_PHPMAILER','true');

/*** adodb4 (prev ver) for pcntlcmd (!?) ***/

require_once('dpc/system/pcntl.lib.php'); 
$page = &new pcntl('
super javascript;

load_extension adodb4 refby _ADODB_; 
super database;

use mail.bounce_driver;

public cms.cmsrt;
public mail.smtpmail;
public bmail.maildbqueue;

',1,true);	 

$ret = _m('maildbqueue.sendmail_daemon use 20+100');
echo $ret;
$time = (microtime(true) - $start)/60;//5.4$_SERVER["REQUEST_TIME_FLOAT"]);// /60;
echo "<!-- 	$time -->";
?>